extern pm_edge *pmVide4cocycle(pm_edge *Root, pm_edge *Cot1, pm_edge *Cot2, pm_edge *Cot3);
extern int pmInSum(pm_edge *Root);
extern int pmCheck1(pm_edge *Edge);
extern void pmC3kernel(pm_edge *Root);
extern void pmFull2to3c(pm_edge *Root);
extern pm_edge *pmGet3c(pm_edge *Root);
extern pm_edge *pmVide2cocycle(pm_edge *Root, pm_edge *Cot1);
extern int pmCheck2(pm_edge *Edge);
extern void pmTri3kernel(pm_edge *Root);
extern pm_edge *pmGet3tri(pm_edge *Root);
extern void pmFull2to3tri(pm_edge *Root);
extern pm_edge *pmVide3cocycle(pm_edge *Root, pm_edge *Cot1, pm_edge *Cot2);
extern int pmCheck3(pm_edge *Edge);
extern void pmTri4kernel(pm_edge *Root);
extern void pmFull2to4tri(pm_edge *Root);
extern pm_edge *pmGet4tri(pm_edge *Root);
extern pm_edge *pmVide2cocycle4r(pm_edge *Root, pm_edge *Cot1);
extern int pmCheck4(pm_edge *Edge);
extern void pmSimplekernel(pm_edge *Root);
extern pm_edge *pmGetsimple4r(pm_edge *Root);
extern void pmFull4rtosimple(pm_edge *Root);
